config/routes.rb
BlackBoard::Application.routes.draw do |map|
  resources :notification_condition_loading_spaces

  resources :notification_condition_freights

  resources :notification_conditions

  resources :notification_condition_sets

  resources :notifications
  resources :notification_items do
    collection do
      post :mark_all_as_read
    end
  end

  resources :white_listed_items do
    collection do
      post :destroy_all
    end
  end

  resources :black_listed_items do
    collection do
      post :destroy_all
    end
  end

  match "setup" => 'setup#index', :as => :setup  
  match "not_seeded" => 'setup#not_seeded', :as => :not_seeded
  match "demo_company" => 'setup#demo_company', :as => :demo_company
  
  match "tolk_import" => 'setup#tolk_import', :as => :tolk_import
  match "tolk_sync_all" => 'setup#tolk_sync', :as => :tolk_sync
  match "tolk_dump_all" => 'setup#tolk_dump_all', :as => :tolk_dump_all
  
  resources :reviews do
    collection do
      get :created
    end
    member do
      post :approve
    end
  end


  resources :people

  resources :loading_spaces do
    collection do
      get :upload
      post :upload
    end
  end
  resources :freights do
    collection do
      get :upload
      post :upload
    end
  end
  
  resources :companies
  resources :stations do
    collection do
      get :autocomplete
    end
  end
  resources :users

  match "about" => "root#about", :as => :about
  match "error" => "root#server-error", :as => :error
  
  resources :users
  resources :user_sessions do
    collection do
      get :demo_login
    end
  end
  
  match "welcome" => 'root#welcome', :as => :after_login
  match "first_steps" => 'root#welcome', :as => :after_company_creation
  
  match "my_profile" => 'users#edit', :as => :my_profile
  match "register" => 'companies#new', :as => :register
  match "forgot_password" => 'user_sessions#forgot_password', :as => :forgot_password
  match "reset_password/:user_id/:password_reset_key" => 'user_sessions#reset_password', :as => :reset_password_with_key
  match "reset_password" => 'user_sessions#reset_password', :as => :reset_password
  match "login" => 'user_sessions#new', :as => :login
  match "logout" => 'user_sessions#destroy', :as => :logout
  
  match "search" => 'search#index', :as => :search
  match "advanced" => 'search#advanced', :as => :advanced_search
  match "dashboard" => 'companies#dashboard', :as => :company_dashboard

  match "contact" => 'contact#index', :as => :contact
  
  root :to => "root#index"
  
  namespace :admin do
    resources :app_configs do
      collection do
        get :reimport_defaults 
      end
    end
    resources :companies
    resources :stations
    resources :freights # BEWARE: not implemented
    resources :loading_spaces # BEWARE: not implemented
    resources :people # BEWARE: not implemented
    resources :reviews # BEWARE: not implemented
    resources :action_recordings
    resources :search_recordings do
      collection do
        get :keyword
      end
    end
    resources :user_roles
    resources :users

    get "monitoring/:action"
    match "monitoring", :to => "monitoring#index", :as => :monitoring

    root :to => "root#index"
    match "search", :to => "search#index", :as => :search
  end












end

app/models/loading_space.rb
# LoadingSpace objects are postings for loading space.
# 
# They have two SiteInfo objects attached for their origin and destination 
# and several LocalizedInfo objects to describe the posting.
#
class LoadingSpace < ActiveRecord::Base
  SITE_ATTRIBUTES = %w(name address address2 zip city country)
  ORIGIN_ATTRIBUTES = SITE_ATTRIBUTES.map { |s| "origin_#{s}" }
  DESTINATION_ATTRIBUTES = SITE_ATTRIBUTES.map { |s| "destination_#{s}" }

  TRANSPORT_TYPE_CHOICES = ::Freight::TRANSPORT_TYPE_CHOICES
  FREQUENCY_CHOICES = %w(once weekly monthly yearly)
  FREE_CAPACITIES_CHOICES = %w(train wagon slots)
  OWN_MEANS_OF_TRANSPORT_CHOICES = Freight::OWN_MEANS_OF_TRANSPORT_CHOICES
  OWN_MEANS_OF_TRANSPORT_PRESENT_CHOICES = Freight::OWN_MEANS_OF_TRANSPORT_PRESENT_CHOICES

  belongs_to :user
  belongs_to :company

  belongs_to :reply_to, :class_name => 'Freight'
  belongs_to :parent, :class_name => 'LoadingSpace'

  belongs_to :origin_station, :class_name => 'Station'
  belongs_to :destination_station, :class_name => 'Station'
  belongs_to :contact_person, :class_name => 'Person'
  has_many :matching_recordings, :as => 'b', :order => 'result DESC', :dependent => :destroy
  searchable

  after_save :create_notification

  has_and_belongs_to_many :company_roles, :uniq => true

  def contact_email
    contact_person.full?(&:email) || company.email
  end

  include ActiveRecord::HasLocalizedInfos
  def localized_infos=(array_of_hashes) # :nodoc:
    localized_infos!(array_of_hashes)
  end
  
  # Returns the given number of matching freight objects for the loading space.
  def matching_freights(limit = 3)
    matching_recordings.limit(limit).map(&:a)
  end
  alias matching_objects matching_freights

  def name # :nodoc:
    if parent.full?
      I18n.t("loading_spaces.common.negotiated_name")
    else
      "#{origin_name} - #{destination_name}"
    end
  end

  def pretty_prefix
    '#A'
  end
  
  def to_search # :nodoc:
    search_str = [:origin, :destination].map { |origin_or_destination|
      [
        self.__send__("#{origin_or_destination}_station").full? { |station|
          [
            station.name, station.numeric_id
          ]
        },
        SITE_ATTRIBUTES.map { |field|
          self.__send__("#{origin_or_destination}_#{field}").full?
        }
      ]
    }.flatten.compact * "\n"
    
    I18n.available_locales.each do |lang|
      search_str << "\n" << [
        localized_infos.where(:lang => lang.to_s).all.map(&:text) * "\n",
        hazmat? ? I18n.t('activerecord.attributes.freight.hazmat', :locale => lang, :default => '') : nil,
        human_attribute_values_in(lang, [:transport_type]),
      ].flatten.compact * "\n"
    end
    search_str.simplify
  end
  
  private
  
  def human_attribute_values_in(lang, *values)
    values.flatten.map { |attr| 
      human_attribute_value(attr, :locale => lang, :default => '').full?
    }.compact
  end

  def create_notification
    if p = self.parent.full?
      Notification.create_for(p.company, self)
    end
  end

  validates_presence_of :user_id
  validates_presence_of :company_id
  
  
  validates_presence_of :contractor
  validates_presence_of :valid_from
  validates_presence_of :valid_until
  
  validates_inclusion_of :frequency, :in => FREQUENCY_CHOICES

  validates_inclusion_of :own_means_of_transport_present, :in => [true, false]
  validates_inclusion_of :own_means_of_transport, :in => OWN_MEANS_OF_TRANSPORT_CHOICES, :if => :own_means_of_transport_present
end

app/controllers/loading_spaces_controller.rb
class LoadingSpacesController < PostingsController
end

app/helpers/loading_spaces_helper.rb
module LoadingSpacesHelper
  def matching_results
    @matching_results ||= resource.matching_objects
  end
end

app/views/loading_spaces/_form.html.erb
<%= semantic_form_for(resource) do |f| %>
  <%= render :partial => "postings/shared_form", :locals => {:f => f} %>

  <%= f.inputs :transport_timeframe do %>
    <%#= localized_info_field f, :transport_text %>
    
    <%#= localized_info_field f, :misc_text %>
    
    <%= f.input :own_means_of_transport_present, :as => :radio, :collection => own_means_of_transport_present_choices %>

    <%= f.input :own_means_of_transport, :collection => collection_choices(Freight, :own_means_of_transport), :include_blank => true %>
    <%= f.input :own_means_of_transport_custom, :as => :string %>

    <%= f.input :free_capacities, :collection => collection_choices(resource.class, :free_capacities), :as => :select %>

  <% end %>

  <%= f.inputs :misc_text, :class => "inputs misc_info" do %>
    <%= f.input :contact_person, :collection => current_company.people %>
  <% end %>

  <%= f.inputs :company_roles do %>
    <%= f.input :company_roles, :as => :check_boxes, :collection => CompanyRole.all.map { |r| [t("activerecord.human_attribute_values.company_role.name.#{r.name}"), r.id] } %>
    <%= f.input :custom_category, :as => :string %>
  <% end %>

  <%= f.buttons do %>
    <%= f.commit_button :label => t("#{controller_name}.#{action_name == 'new' ? 'new' : 'edit' }.submit") %>
  <% end %>
<% end %>

app/views/loading_spaces/_search_result.html.erb
<div class="image"><%= image_tag "type/#{result.class.to_s.underscore}.png" %></div>
<div class="text">
  <%= link_to result.company.name, {:controller => result.class.to_s.pluralize.underscore, :action => 'show', :id => result, :search_recording_id => @search_recording.full?(&:id)} %><br>
  <b><%= result.origin_name %></b> <%= l(result.origin_date, :format => :short) if result.origin_date %>
  -
  <b><%= result.destination_name %></b> <%= l(result.destination_date, :format => :short) if result.destination_date %>
</div>
<%= clear_both %>

app/views/loading_spaces/edit.html.erb
<div class="box">
  <h3><%= t("loading_spaces.edit.header") %></h3>
  <%= render 'form' %>
</div>

app/views/loading_spaces/index.html.erb
<%= partial "toolbar_postings" %>

<div class="box">
  <h3><%= t("loading_spaces.index.header#{'_query' if @q}", :query => @q) %></h3>
  <p>
    <%= t('loading_spaces.index.intro') %>
  </p>
  
  <%= render :partial => "postings/postings" %>
  <%= will_paginate(collection).to_s.html_safe %>
</div>

app/views/loading_spaces/new.html.erb
<div class="box">
  <h3><%= t("loading_spaces.new.header") %></h3>
  <p>
    <%= t("loading_spaces.common.required_field_hint") %>
  </p>
  <%= render 'form' %>
</div>

app/views/loading_spaces/show.html.erb
<% content_for(:toolbar) do %>
  <% if resource.company == current_company %>
    <div class="float_left">
      <%= link_btn t('loading_spaces.common.template_link'), new_resource_url(:parent_id => resource.id), :icon => 'reply' %>
    </div>
    <div class="float_right">
      <%= link_btn t("loading_spaces.common.edit_link"), edit_loading_space_path(@loading_space), :icon => 'edit' %>
      <%= link_btn t("loading_spaces.common.delete_link"), loading_space_path(@loading_space), :method => :delete, :confirm => t('common.confirm'), :class => 'destroy' %>
    </div>
  <% else %>
    <%= link_btn t('loading_spaces.common.negotiate_link'), new_loading_space_path(:parent_id => resource.id), :icon => 'reply' %>
    <%= link_btn t('loading_spaces.common.reply_to_link'), new_freight_path(:reply_to_id => resource.id), :icon => 'reply' %>
    <% if resource.contact_email.full? %>
      <%= link_btn t('loading_spaces.common.contact_to_link'), t('loading_spaces.common.contact_to_href', :email => resource.contact_email, :name => resource.pretty_id, :url => @resource_url), :icon => 'next' %>
    <% end %>
  <% end %>
<% end %>

<div class="box">
  <% if resource.reply_to.full? %>
    <div class="success">
      <%= auto_link(t("loading_spaces.show.is_reply_to", :name => resource.reply_to.pretty_id)).html_safe %>
    </div>
  <% end %>

  <% if resource.parent_id.full? %>
    <div class="notice">
      <%= t("loading_spaces.show.is_in_negotiation") %>
    </div>
  <% end %>

  <h3><%= resource_class.human_attribute_name(:contractor) %>: <%= resource.contractor %></h3>
  <div>
    <%= resource_class.human_attribute_name(:valid_until) %>
    <%= l resource.valid_until, :format => :date %>
  </div>

  <hr>

  <%= render :partial => "postings/origin_and_destination" %>

  <hr>

  <%= render :partial => "postings/frequency" %>

  <h3><%= t("loading_spaces.show.transport_description") %></h3>

  <%= posting_attribute :free_capacities, :humanize => true %>

  <%= posting_attribute :own_means_of_transport_present, :value => resource.own_means_of_transport_present ? "choice_true" : "choice_false", :humanize => true %>
  <% if resource.own_means_of_transport_present? %>
    <%= posting_attribute :own_means_of_transport, :humanize => true, :dependent => true %>
    <%= posting_attribute :own_means_of_transport_custom, :dependent => true if resource.own_means_of_transport == "custom" %>
  <% end %>

  <!--
  <tr>
    <th><%= resource_class.human_attribute_name(:transport_text) %></th>
    <td><%= localized_info(@loading_space, :transport_text) %></td>
  </tr>
  <tr>
    <th><%= resource_class.human_attribute_name(:misc_text) %></th>
    <td><%= localized_info(@loading_space, :misc_text) %></td>
  </tr>
  -->

</div>

<div class="box search_results_box" style="display:none">
  <h3><%= t "search.common.results.header" %></h3>
  <% if matching_results.full? %>
    <ul class="search_results action_list">
    <% matching_results.each do |result| %>
      <li class="<%= highlight_in_search?(result) ? 'highlight' : '' %>">
        <% if template_exists?("/#{result.class.to_s.tableize}/_search_result")%>
          <%= render :partial => "/#{result.class.to_s.tableize}/search_result", :locals => {:result => result} %>
        <% else %>
          <% if result.is_a?(Posting) %>
            <%= link_to "#{result.origin_station.name} - #{result.destination_station.name}", result %>
          <% else %>
            <%= link_to result.name, result %>
          <% end %>
        <% end %>
      </li>
    <% end %>
    </ul>
  <% end %>
</div>

<% content_for(:sidebar) do %>
  <%= render_person_info(resource.contact_person) if resource.contact_person %>
  <%= render_company_info(resource.company) %>
<% end %>