config/routes.rb
BlackBoard::Application.routes.draw do |map|
  resources :notification_condition_loading_spaces

  resources :notification_condition_freights

  resources :notification_conditions

  resources :notification_condition_sets

  resources :notifications
  resources :notification_items do
    collection do
      post :mark_all_as_read
    end
  end

  resources :white_listed_items do
    collection do
      post :destroy_all
    end
  end

  resources :black_listed_items do
    collection do
      post :destroy_all
    end
  end

  match "setup" => 'setup#index', :as => :setup  
  match "not_seeded" => 'setup#not_seeded', :as => :not_seeded
  match "demo_company" => 'setup#demo_company', :as => :demo_company
  
  match "tolk_import" => 'setup#tolk_import', :as => :tolk_import
  match "tolk_sync_all" => 'setup#tolk_sync', :as => :tolk_sync
  match "tolk_dump_all" => 'setup#tolk_dump_all', :as => :tolk_dump_all
  
  resources :reviews do
    collection do
      get :created
    end
    member do
      post :approve
    end
  end


  resources :people

  resources :loading_spaces do
    collection do
      get :upload
      post :upload
    end
  end
  resources :freights do
    collection do
      get :upload
      post :upload
    end
  end
  
  resources :companies
  resources :stations do
    collection do
      get :autocomplete
    end
  end
  resources :users

  match "about" => "root#about", :as => :about
  match "error" => "root#server-error", :as => :error
  
  resources :users
  resources :user_sessions do
    collection do
      get :demo_login
    end
  end
  
  match "welcome" => 'root#welcome', :as => :after_login
  match "first_steps" => 'root#welcome', :as => :after_company_creation
  
  match "my_profile" => 'users#edit', :as => :my_profile
  match "register" => 'companies#new', :as => :register
  match "forgot_password" => 'user_sessions#forgot_password', :as => :forgot_password
  match "reset_password/:user_id/:password_reset_key" => 'user_sessions#reset_password', :as => :reset_password_with_key
  match "reset_password" => 'user_sessions#reset_password', :as => :reset_password
  match "login" => 'user_sessions#new', :as => :login
  match "logout" => 'user_sessions#destroy', :as => :logout
  
  match "search" => 'search#index', :as => :search
  match "advanced" => 'search#advanced', :as => :advanced_search
  match "dashboard" => 'companies#dashboard', :as => :company_dashboard

  match "contact" => 'contact#index', :as => :contact
  
  root :to => "root#index"
  
  namespace :admin do
    resources :app_configs do
      collection do
        get :reimport_defaults 
      end
    end
    resources :companies
    resources :stations
    resources :freights # BEWARE: not implemented
    resources :loading_spaces # BEWARE: not implemented
    resources :people # BEWARE: not implemented
    resources :reviews # BEWARE: not implemented
    resources :action_recordings
    resources :search_recordings do
      collection do
        get :keyword
      end
    end
    resources :user_roles
    resources :users

    get "monitoring/:action"
    match "monitoring", :to => "monitoring#index", :as => :monitoring

    root :to => "root#index"
    match "search", :to => "search#index", :as => :search
  end












end

app/models/company.rb
# Company objects represent the organisation of a User.
# 
# Each Company has different types of users, e.g. admins.
class Company < ActiveRecord::Base
  searchable
  has_and_belongs_to_many :company_roles, :uniq => true
  has_many :users, :dependent => :destroy
  has_many :people, :through => :users
  belongs_to :contact_person, :class_name => 'Person'
  has_many :action_recordings, :order => 'created_at DESC', :dependent => :destroy
  has_many :reviews, :order => 'created_at DESC', :dependent => :destroy
  has_many :freights, :order => 'created_at DESC', :dependent => :destroy
  has_many :loading_spaces, :order => 'created_at DESC', :dependent => :destroy
  has_many :black_listed_items, :dependent => :destroy
  has_many :white_listed_items, :dependent => :destroy
  
  # Returns all approved reviews for the company.
  def approved_reviews
    reviews.where('approved_by_id IS NOT NULL')
  end

  def black_listed?(record)
    arel = black_listed_items.where(:item_type => record.class.to_s, :item_id => record.id)
    arel.count > 0
  end

  def white_listed?(record)
    arel = white_listed_items.where(:item_type => record.class.to_s, :item_id => record.id)
    arel.count > 0
  end

  include ActiveRecord::HasLocalizedInfos
  def localized_infos=(array_of_hashes) # :nodoc:
    localized_infos!(array_of_hashes)
  end
  
  # For permission handling
  def company # :nodoc:
    self
  end
  
  # Ensures there is at least one <tt>:company_admin</tt> left in this 
  # company.
  # If no admin can be found, the first user of the company is 
  # assigned the admin role.
  def ensure_admin
    unless users.any? { |u| u.is?(:company_admin) }
      if (u = users.first) && (admin_role = UserRole[:company_admin])
        u.user_roles << admin_role
      end
    end
  end
  
  # Returns all unapproved reviews for the company.
  def unapproved_reviews
    reviews.where('approved_by_id IS NULL')
  end
  
  def website # :nodoc:
    address = self[:website]
    if address.blank? || address =~ /^\w+\:\/\//
      address
    else
      "http://#{address}"
    end
  end

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::BaseController
end

app/controllers/companies_controller.rb
# The CompaniesController provides functionality for managing a user's company
# as well as the actual 'Create a new Account'-screen.
class CompaniesController < RemoteController
  login_required :except => [:new, :create]
  same_company_required :except => [:dashboard, :index, :new, :create, :show, :freights, :loading_spaces]
  role_required [:company_admin, :company_employee], :except => [:dashboard, :index, :new, :create, :show, :freights, :loading_spaces]
  
  # The dashboard action provides a general overview of the company's 
  # activities.
  def dashboard
    actions = %w(create update destroy)
    @company = current_company
    @recordings = current_company.action_recordings.where(:action => actions).limit(50)
  end

  # The Companies#new action is actually the "Create a new Account"-screen
  # a user sees when he originally signs up for the freight exchange.
  def new
    @company = Company.new
    @user = User.new(:user_roles => [UserRole[:company_admin]])
    @user.build_person
  end
  
  def create
    @company = Company.new(params[:company])
    @user = User.new(params[:user])
    @company.valid? # to populate @company.errors
    if @user.valid? && @company.valid?
      @company.save!
      @user.company = @company
      @user.save!
      redirect_to after_login_url
    else
      render :action => :new
    end
  end
  
  private
  
  def filter_collection!
    if params[:black_listed].full?
      self.collection = collection.where(:id => blocked_company_ids)
    elsif params[:white_listed].full?
      ids = current_company.white_listed_items.where(:item_type => 'Company').collect(&:item_id)
      self.collection = collection.where(:id => ids)
    else
      if blocked_company_ids.full?
        self.collection = collection.where("id NOT IN (?)", blocked_company_ids)
      end
    end
  end

  def order_collection!
    order = if params[:order].blank? || params[:order] == 'name'
      'UPPER(name) ASC'
    elsif params[:order] == 'created_at'
      'created_at DESC'
    end
    self.collection = collection.order(order)    
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def registering_new_account?
    current_user.blank?
  end
end

app/views/companies/_form.html.erb
<%= semantic_form_for(@company) do |f| %>
  <%= f.inputs :company_name do %>
    <%= f.input :name %>

    <%= f.inputs :company_roles do %>
      <%= f.input :company_roles, :as => :check_boxes, :collection => CompanyRole.all.map { |r| [t("activerecord.human_attribute_values.company_role.name.#{r.name}"), r.id] } %>
      <%= f.input :custom_category, :as => :string %>
    <% end %>
  <% end %>
  <%= f.inputs :company_address do %>
    <%= f.input :address %>
    <%= f.input :address2 %>
    <%= f.input :zip %>
    <%= f.input :city %>
    <%= f.input :country, :as => :string %>
  <% end %>

  <%= f.inputs :company_contact_person do %>
    <%= f.input :contact_person, :collection => current_company.people %>
  <% end %>
  <%= f.inputs :company_contact do %>
    <%= f.input :phone %>
    <%= f.input :fax %>
    <%= f.input :email %>
    <%= f.input :website %>
  <% end %>

  <%= f.inputs :company_registries do %>
    <%= f.input :commercial_register_entry %>
    <%= f.input :vat_id %>
  <% end %>

  <% obsolete do %>
    <%= f.inputs :company_misc do %>
      <%= localized_info_fields f, :misc_text %>
    <% end %>
  <% end %>

  <%= f.buttons %>
<% end %>

app/views/companies/dashboard.html.erb
<%= partial "toolbar_company" %>

<div class="box">
  <h3><%= t("companies.dashboard.header") %></h3>
  <p>
    <%= t('companies.dashboard.intro') %>
  </p>
  
  <%= partial :recordings, :locals => {:recordings => @recordings} %>
</div>

<% content_for(:sidebar) do %>
  <h3 class="info"><%= t("companies.dashboard.sidebar_person_info_title") %></h3>
<% end %>
<%= render_person_info current_person %>

<% content_for(:sidebar) do %>
  <h3 class="info"><%= t("companies.dashboard.sidebar_company_info_title") %></h3>
<% end %>
<%= render_company_info @company %>

app/views/companies/edit.html.erb
<div class="box">
  <h3><%= t("companies.edit.header") %></h3>
  <p>
    <%= t("common.required_field_hint") %>
  </p>
  <%= render 'form' %>
</div>

app/views/companies/freights.html.erb
<%= partial "toolbar_posting_filters" %>

<div class="box">
  <h3>
    <%= float_tag t("companies.freights.header", :company => resource.name) %>
    <% if resource == current_company %>
      <%= link_btn t("freights.common.new_link"), new_freight_path, :icon => 'new' %>
    <% end %>
    <%= clear_both %>
  </h3>
  <p>
    <%= t('companies.freights.intro') %>
  </p>

  <%= render :partial => "postings/postings" %>
</div>

app/views/companies/index.html.erb
<% content_for(:toolbar) do %>
  <div class="float_left">
    <%#= link_btn_unless_current t("companies.index.all_companies"), companies_path %>
    <%= link_btn_unless params.size == 2 || params[:order] == 'name', t("companies.index.filter_by_name"), :order => 'name' %>
    <%= link_btn_unless_current t("companies.index.filter_by_created_at"), :order => 'created_at' %>
  </div>
  <div class="float_right">
    <%= link_btn_unless_current t("companies.index.white_listed_companies"), :white_listed => true %>
    <%= link_btn_unless_current t("companies.index.black_listed_companies"), :black_listed => true %>
  </div>
<% end %>

<div class="box">
  <h3><%= link_to_unless_current t("companies.index.header"), companies_path %></h3>
  <p>
    <%= t('companies.index.intro') %>
  </p>
  <table class="companies">
    <thead>
      <tr>
        <th><%= t('companies.index.table.headers.name') %></th>
        <th><%= t('companies.index.table.headers.zip') %></th>
        <th><%= t('companies.index.table.headers.city') %></th>
        <th><%= t('companies.index.table.headers.country') %></th>
      </tr>
    </thead>
    <tbody>
      <% collection.each do |ar| %>
        <tr class="<%= 'white_listed' if white_listed?(ar) %><%= ' black_listed' if black_listed?(ar) %>">
          <td class="company_name"><%= link_to ar.name, ar, :class => ar.class.to_s.underscore %></td>
          <td class="company_zip"><%= ar.zip %></td>
          <td class="company_city"><%= ar.city %></td>
          <td class="company_country"><%= ar.country %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate(collection).to_s.html_safe %>
</div>

app/views/companies/loading_spaces.html.erb
<%= partial "toolbar_posting_filters" %>

<div class="box">
  <h3>
    <%= float_tag t("companies.loading_spaces.header", :company => resource.name) %>
    <% if resource == current_company %>
      <%= link_btn t("loading_spaces.common.new_link"), new_loading_space_path, :icon => 'new' %>
    <% end %>
    <%= clear_both %>
  </h3>
  <p>
    <%= t('companies.loading_spaces.intro') %>
  </p>

  <%= render :partial => "postings/postings" %>
</div>

app/views/companies/new.html.erb
<div class="box">
  <h3><%= t("companies.new.header") %></h3>
  <p>
    <%= t("companies.new.intro") %>
  </p>
  <%= semantic_form_for(@user, :url => companies_url) do |f| %>
    <fieldset class="inputs">
      <legend><span><%= t("formtastic.titles.for_company") %></span></legend>
      <ol>
        <li class="string optional<%= ' error' if @company.errors.full? %>">
          <%= label :company, :name %> <%= text_field :company, :name, :size => 50, :maxlength => 255 %>
          <%= @company.errors[:name] %>
        </li>
      </ol>
    </fieldset>
    
    <%= f.semantic_fields_for :person do |f_person| %>
      <%= f_person.inputs :person_name do %>
        <%= f_person.input :gender, :collection => collection_choices(Person, :gender), :as => :select, :include_blank => false %>
        <%= f_person.input :first_name %>
        <%= f_person.input :last_name %>
      <% end %>
    <% end %>

      <%= render :partial => "/users/form_content", :locals => {:f => f} %>
    <%= f.buttons %>
  <% end %>
  
  <%= javascript_tag <<-JS
    var user_login = jQuery('#user_login').value;
    var dont_auto_fill_user_login = !(user_login == '' || user_login == undefined);
    jQuery(function($) {
      jQuery('#user_login').focus(function() { dont_auto_fill_user_login = true; });
      jQuery('#company_name').keyup(function() {
        if( !dont_auto_fill_user_login ) {
          var login = login_from_name(this.value);
          jQuery('#user_login').val(login);
        }
      }).change();
    });
  JS
  %>
</div>

app/views/companies/show.html.erb
<%= partial "toolbar_company" %>

<% if misc_text = localized_info(@company, :misc_text) %>
  <h2><%= t("companies.show.header_misc_text") %></h2>
  <div class="box">
    <%= misc_text %>
  </div>
<% end %>

<h2><%= t("companies.show.header_people") %></h2>
<% @company.people.each do |person| %>
  <div class="box">
    <h3><%= t "common.sidebar.person_information.header" %></h3>

    <table>
      <thead>
        <tr>
          <th colspan="2"><b><%= person.name %></b></th>
        </tr>
      </thead>
      <% if person[:job_description].full? %>
        <tr>
          <td><%= contact_info(person, :job_description) %></td>
          <th></th>
        </tr>
      <% end %>
      <% %w(phone fax email website).each do |attr| %>
        <% if person[attr].full? %>
          <tr>
            <th><%= Person.human_attribute_name(attr) %></th>
            <td><%= contact_info(person, attr)%></td>
          </tr>
        <% end %>
      <% end %>
      <% if misc_text = localized_info(person, :misc_text) %>
        <tr>
          <th><%= t("activerecord.attributes.person.localized_infos.misc_text") %></th>
          <td><%= misc_text %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

<% if reviews = @company.approved_reviews.presence %>
  <h2><%= t("companies.show.header_reviews") %></h2>
  <% reviews.each do |review| %>
    <div class="box">
      <table>
        <tr>
          <th><%= Review.human_attribute_name(:author_company) %></th>
          <td><%= link_to_item review.author_company %></td>
        </tr>
        <tr>
          <th><%= Review.human_attribute_name(:author_user) %></th>
          <td><%= link_to_item review.author_user %></td>
        </tr>
        <tr>
          <th><%= Review.human_attribute_name(:text) %></th>
          <td><%= review.text %></td>
        </tr>
      </table>
    </div>
  <% end %>
<% end %>


<%= render_person_info(@company.contact_person) if @company.contact_person %>
<%= render_company_info(@company) %>