config/routes.rb
BlackBoard::Application.routes.draw do |map|
  resources :notification_condition_loading_spaces

  resources :notification_condition_freights

  resources :notification_conditions

  resources :notification_condition_sets

  resources :notifications
  resources :notification_items do
    collection do
      post :mark_all_as_read
    end
  end

  resources :white_listed_items do
    collection do
      post :destroy_all
    end
  end

  resources :black_listed_items do
    collection do
      post :destroy_all
    end
  end

  match "setup" => 'setup#index', :as => :setup  
  match "not_seeded" => 'setup#not_seeded', :as => :not_seeded
  match "demo_company" => 'setup#demo_company', :as => :demo_company
  
  match "tolk_import" => 'setup#tolk_import', :as => :tolk_import
  match "tolk_sync_all" => 'setup#tolk_sync', :as => :tolk_sync
  match "tolk_dump_all" => 'setup#tolk_dump_all', :as => :tolk_dump_all
  
  resources :reviews do
    collection do
      get :created
    end
    member do
      post :approve
    end
  end


  resources :people

  resources :loading_spaces do
    collection do
      get :upload
      post :upload
    end
  end
  resources :freights do
    collection do
      get :upload
      post :upload
    end
  end
  
  resources :companies
  resources :stations do
    collection do
      get :autocomplete
    end
  end
  resources :users

  match "about" => "root#about", :as => :about
  match "error" => "root#server-error", :as => :error
  
  resources :users
  resources :user_sessions do
    collection do
      get :demo_login
    end
  end
  
  match "welcome" => 'root#welcome', :as => :after_login
  match "first_steps" => 'root#welcome', :as => :after_company_creation
  
  match "my_profile" => 'users#edit', :as => :my_profile
  match "register" => 'companies#new', :as => :register
  match "forgot_password" => 'user_sessions#forgot_password', :as => :forgot_password
  match "reset_password/:user_id/:password_reset_key" => 'user_sessions#reset_password', :as => :reset_password_with_key
  match "reset_password" => 'user_sessions#reset_password', :as => :reset_password
  match "login" => 'user_sessions#new', :as => :login
  match "logout" => 'user_sessions#destroy', :as => :logout
  
  match "search" => 'search#index', :as => :search
  match "advanced" => 'search#advanced', :as => :advanced_search
  match "dashboard" => 'companies#dashboard', :as => :company_dashboard

  match "contact" => 'contact#index', :as => :contact
  
  root :to => "root#index"
  
  namespace :admin do
    resources :app_configs do
      collection do
        get :reimport_defaults 
      end
    end
    resources :companies
    resources :stations
    resources :freights # BEWARE: not implemented
    resources :loading_spaces # BEWARE: not implemented
    resources :people # BEWARE: not implemented
    resources :reviews # BEWARE: not implemented
    resources :action_recordings
    resources :search_recordings do
      collection do
        get :keyword
      end
    end
    resources :user_roles
    resources :users

    get "monitoring/:action"
    match "monitoring", :to => "monitoring#index", :as => :monitoring

    root :to => "root#index"
    match "search", :to => "search#index", :as => :search
  end












end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  login_required
  
  def index
    if request.post?
      if text = params[:text].full?
        Contact.contact(text, current_user).deliver
        redirect_to :sent => true
      end
    end
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/_imprint.html.erb
<h3>Anbieterkennzeichnung</h3>
<p>Institut für Produktion und Industrielles Informationsmanagement<br>Direktor: Univ.-Prof. Dr. Stephan Zelewski<br>Universität Duisburg-Essen, Campus Essen<br>Fakultät für Wirtschaftswissenschaften<br>Universitätsstr. 9<br>D-45141 Essen </p>

<h3>Haftungsausschuss</h3>
<p>1. Inhalt des Onlineangebotes 
</p>
<p>Der Anbieter übernimmt keinerlei Gewähr für die Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen. Haftungsansprüche gegen den Anbieter, welche sich auf Schäden materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen oder durch die Nutzung fehlerhafter oder unvollständiger Informationen verursacht wurden, sind grundsätzlich ausgeschlossen, sofern seitens des Anbieters kein nachweislich vorsätzliches oder grob fahrlässiges Verschulden vorliegt. Alle Angebote sind freibleibend und unverbindlich. Der Anbieter behält es sich ausdrücklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen. 
</p>
<p>&nbsp;</p>
<p>2. Verweise und Links 
</p>
<p>Mit Urteil vom 12. Mai 1998 - 312 O 85/98 - "Haftung für Links" hat das Landgericht (LG) in Hamburg entschieden, dass man durch die Anbringung eines Links die Inhalte der gelinkten Seite ggf. mit zu verantworten hat. Dies kann - so das LG - nur dadurch verhindert werden, indem man sich ausdrücklich von diesen Inhalten distanziert. 
</p>
<p>Hiermit distanzieren wir uns ausdrücklich von allen Inhalten aller gelinkten Seiten auf unserer Homepage. Diese Erklärung gilt für alle auf unserer Homepage angebrachten Links. 
</p>
<p>Auf die Gestaltung, die Inhalte und die Urheberschaft der verlinkten/verknüpften Seiten hat der Anbieter keinerlei Einfluss. Deshalb distanziert er sich hiermit ausdrücklich von allen Inhalten aller verlinkten/verknüpften Seiten. Diese Feststellung gilt für alle innerhalb des eigenen Internetangebotes gesetzten Links und Verweise sowie für Fremdeinträge in vom Anbieter eingerichteten Gästebüchern, Diskussionsforen und Mailinglisten. Für illegale, fehlerhafte oder unvollständige Inhalte und insbesondere für Schäden, die aus der Nutzung oder Nichtnutzung solcherart dargebotener Informationen entstehen, haftet allein der Anbieter der Seite, auf welche verwiesen wurde, nicht derjenige, der über Links auf die jeweilige Veröffentlichung lediglich verweist. 
</p>
<p>&nbsp;</p>
<p>3. Urheber- und Kennzeichenrecht 
</p>
<p>Der Anbieter ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, von ihm selbst erstellte Grafiken, Tondokumente, Videosequenzen und Texte zu nutzen oder auf lizenzfreie Grafiken, Tondokumente, Videosequenzen und Texte zurückzugreifen. Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte geschützten Marken- und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils gültigen Kennzeichenrechts und den Besitzrechten der jeweils eingetragenen Eigentümer. Allein aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter geschützt sind. Das Copyright für veröffentlichte, vom Anbieter selbst erstellte Objekte bleibt allein beim Anbieter der Seiten. Eine Vervielfältigung oder Verwendung solcher Grafiken, Tondokumente, Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdrückliche Zustimmung des Anbieters nicht gestattet. 
</p>
<p>&nbsp;</p>
<p>4. Datenschutz 
</p>
<p>Sofern innerhalb des Internetangebotes die Möglichkeit zur Eingabe persönlicher oder geschäftlicher Daten (E-Mail-Adressen, Namen, Anschriften) besteht, so erfolgt die Preisgabe dieser Daten seitens des Nutzers auf ausdrücklich freiwilliger Basis. Die Inanspruchnahme und Bezahlung aller angebotenen Dienste ist - soweit technisch möglich und zumutbar - auch ohne Angabe solcher Daten oder unter Angabe anonymisierter Daten oder eines Pseudonyms gestattet. 
</p>
<p>&nbsp;</p>
<p>5. Rechtswirksamkeit dieses Haftungsausschlusses 
</p>
<p>Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollständig entsprechen sollten, bleiben die übrigen Teile des Dokumentes in ihrem Inhalt und ihrer Gültigkeit davon unberührt. </p>

app/views/contact/contact.text.erb
<%= @user.name %> contacted you!

===========================================================

<%= @text %>

===========================================================

<%= @user.name %>

Profile:   http://<%= AppConfig[:domain] %><%= person_path(@person) %>
<%- %w(phone fax email website).each do |attr| -%>
<%= (Person.human_attribute_name(attr) + ':').ljust(10) %> <%= @person[attr].full? || '-' %>
<%- end -%>
    
<%= @company.name %>

Profile:   http://<%= AppConfig[:domain] %><%= company_path(@company) %>
<%- %w(phone fax email website).each do |attr| -%>
<%= (Company.human_attribute_name(attr) + ':').ljust(10) %> <%= @company[attr].full? || '-' %>
<%- end -%>

app/views/contact/index.html.erb
<div class="box">
  <h3><%= t("contact.index.header") %></h3>
  
  <% if params[:sent] %>
  <div class="notice"><%= t("contact.index.sent") %></div>
  <% else %>
    <p>
      <%= t("contact.index.intro") %>
    </p>
    <%= form_tag do %>
      <%= text_area_tag :text, "" %><br>
      <%= submit_tag t("contact.index.submit") %>
    <% end %>
  <% end %>
</div>