config/routes.rb
BlackBoard::Application.routes.draw do |map|
  resources :notification_condition_loading_spaces

  resources :notification_condition_freights

  resources :notification_conditions

  resources :notification_condition_sets

  resources :notifications
  resources :notification_items do
    collection do
      post :mark_all_as_read
    end
  end

  resources :white_listed_items do
    collection do
      post :destroy_all
    end
  end

  resources :black_listed_items do
    collection do
      post :destroy_all
    end
  end

  match "setup" => 'setup#index', :as => :setup  
  match "not_seeded" => 'setup#not_seeded', :as => :not_seeded
  match "demo_company" => 'setup#demo_company', :as => :demo_company
  
  match "tolk_import" => 'setup#tolk_import', :as => :tolk_import
  match "tolk_sync_all" => 'setup#tolk_sync', :as => :tolk_sync
  match "tolk_dump_all" => 'setup#tolk_dump_all', :as => :tolk_dump_all
  
  resources :reviews do
    collection do
      get :created
    end
    member do
      post :approve
    end
  end


  resources :people

  resources :loading_spaces do
    collection do
      get :upload
      post :upload
    end
  end
  resources :freights do
    collection do
      get :upload
      post :upload
    end
  end
  
  resources :companies
  resources :stations do
    collection do
      get :autocomplete
    end
  end
  resources :users

  match "about" => "root#about", :as => :about
  match "error" => "root#server-error", :as => :error
  
  resources :users
  resources :user_sessions do
    collection do
      get :demo_login
    end
  end
  
  match "welcome" => 'root#welcome', :as => :after_login
  match "first_steps" => 'root#welcome', :as => :after_company_creation
  
  match "my_profile" => 'users#edit', :as => :my_profile
  match "register" => 'companies#new', :as => :register
  match "forgot_password" => 'user_sessions#forgot_password', :as => :forgot_password
  match "reset_password/:user_id/:password_reset_key" => 'user_sessions#reset_password', :as => :reset_password_with_key
  match "reset_password" => 'user_sessions#reset_password', :as => :reset_password
  match "login" => 'user_sessions#new', :as => :login
  match "logout" => 'user_sessions#destroy', :as => :logout
  
  match "search" => 'search#index', :as => :search
  match "advanced" => 'search#advanced', :as => :advanced_search
  match "dashboard" => 'companies#dashboard', :as => :company_dashboard

  match "contact" => 'contact#index', :as => :contact
  
  root :to => "root#index"
  
  namespace :admin do
    resources :app_configs do
      collection do
        get :reimport_defaults 
      end
    end
    resources :companies
    resources :stations
    resources :freights # BEWARE: not implemented
    resources :loading_spaces # BEWARE: not implemented
    resources :people # BEWARE: not implemented
    resources :reviews # BEWARE: not implemented
    resources :action_recordings
    resources :search_recordings do
      collection do
        get :keyword
      end
    end
    resources :user_roles
    resources :users

    get "monitoring/:action"
    match "monitoring", :to => "monitoring#index", :as => :monitoring

    root :to => "root#index"
    match "search", :to => "search#index", :as => :search
  end












end

app/helpers/partial_helper.rb
module PartialHelper
  # Renders a partial taking into account the current user's UserRole objects.
  def partial(partial, options = {})
    subs = current_user.full? { |user| user.roles } || []
    subs << :admin if admin?
    render options.merge(:partial => search_for_partial(partial, subs))
  end
  
  def search_for_partial(partial, sub_dirs, views_dirs = [controller_name, 'partials']) # :nodoc:
    sub_dirs << '' unless sub_dirs.include?('')
    views_dirs.each do |view_dir|
      sub_dirs.each do |sub_dir|
        sub_dir = sub_dir.full? { |d| "#{d}/" }.to_s
        if template_exists?("/#{view_dir}/#{sub_dir}_#{partial}")
          return "/#{view_dir}/#{sub_dir}#{partial}"
        end
      end
    end
    raise "partial not found: #{partial} (sub_dirs: #{sub_dirs.inspect})"
  end
end

app/views/partials/admin/_edit.html.erb
<div class="box">
  <%= render 'form' %>
</div>

app/views/partials/admin/_form.html.erb
<%= semantic_form_for(resource, :url => resource.new_record? ? collection_url : resource_url) do |f| %>
  <%= f.inputs %>
  <%= f.buttons %>
<% end %>

app/views/partials/admin/_header.html.erb
<div class="header">
  <div id="top-navigation">
    <div class="navigation-left">
      <ul class="navigation">
          <li><%= navi_to_unless controller?(:setup), t("admin.common.navi.setup"), setup_path %></li>
          <% if false %>
            <li><%= navi_to_unless controller?(:action_recordings), t("admin.common.navi.action_recordings"), admin_action_recordings_path %></li>
            <li><%= navi_to_unless controller?(:search_recordings), t("admin.common.navi.search_recordings"), admin_search_recordings_path %></li>
          <% end  %>
          <li><%= navi_to_unless controller?(:monitoring), t("admin.common.navi.monitoring"), admin_monitoring_path %></li>
          <li><%= navi_to_unless controller?(:companies), t("admin.common.navi.companies"), admin_companies_path %></li>
          <li><%= navi_to_unless controller?(:users), t("admin.common.navi.users"), admin_users_path %></li>
      </ul>
    </div>
    <div class="navigation-right">
      <ul class="navigation">
        <ul class="navigation">
          <li><%= navi_to_unless controller?(:stations), t("admin.common.navi.stations"), admin_stations_path %></li>
          <li><%= navi_to_unless controller?(:user_roles), t("admin.common.navi.user_roles"), admin_user_roles_path %></li>
          <li><%= navi_to_unless controller?(:app_configs), t("admin.common.navi.app_configs"), admin_app_configs_path %></li>
          <li class="last"><%= link_to image_tag("logout.png") + " " + t("admin.common.navi.back_to_app"), root_path, :class => 'frontend' %></li>
        </ul>
      </ul>
    </div>
    <%= clear_both %>
  </div>
  <div class="container" id="header">
    <div class="span-24 last" id="first-header">
      <%#= link_to image_tag('home_logo.gif'), root_url %>
      <div class="float_left">
        <h2 style="float: left; font-weight: bolder; padding-top: 10px"><%= link_to t("admin.common.navi.home"), admin_root_path, :style => "text-decoration: none; color: #666;" %></h2>
      </div>
      <div class="float_left">

        <div id="search_form">
          <%= form_tag contextual_search_path, :method => :get do %>
            <div class="input-wrapper"><%= link_to_function t("admin.#{contextual_search_controller}.common.search-label"), "void(0);", :id => "search-label", :class => "search-label search-label-#{contextual_search_controller}" %><%= text_field_tag :q, h(params[:q]), :autocomplete => :off %><%= image_submit_tag("search_button.png") %></div>
            <div class="advanced-search-wrapper">
              <div id="advanced-search-controls"<%=  ' style="display:none"'.html_safe unless show_search_options? %>>
                <label for="search_case_sensitive">
                  <input type="checkbox" id="search_case_sensitive" name="case_sensitive" value="1"<%= ' checked="checked"'.html_safe if params[:case_sensitive].full? %>>
                  <%=  t("search.options.case_sensitive") %>
                </label>
                <label for="search_whole_words">
                  <input type="checkbox" id="search_whole_words" name="whole_words" value="1"<%= ' checked="checked"'.html_safe if params[:whole_words].full? %>>
                  <%=  t("search.options.whole_words") %>
                </label>
              </div>
              <%=  link_to_function t("search.options.link"), "$('#advanced-search-controls').show(); $(this).remove()" unless show_search_options? %>
            </div>
          <% end %>
        </div>
      </div>
      <div id="search-label-popover">
         <div class="header">
          <%= "Suche ändern" %>
         </div>
         <div class="content">
           <% %w(app_configs companies stations users).each do |context| %>
             <% text = t("admin.#{context}.common.search-label") %>
             <%= link_to_function text, "switchSearchContext('admin/#{context}', '#{text}');", :id => "", :class => "search-label search-label-#{context}" %>
           <% end %>
         </div>
       </div>
      <%= clear_both %>
    </div>

    <div class="container" id="second-header">
      <ul class="navigation navigation-left">
        <!--
        -->
      </ul>
      <ul class="navigation navigation-right">

      </ul>
    </div>
  </div>
</div>

app/views/partials/admin/_index.html.erb
<% content_for(:toolbar) do %>
  <div class="float_left">
    <% %w(id name login created_at).each do |order| %>
      <% if order == 'id' || resource_class.new.attributes.keys.include?(order) %>
        <%= link_btn_unless (params[:order].blank? && order == default_order_param.to_s) || params[:order] == order, t("admin.common.filter_by_#{order}"), {:order => order} %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/partials/admin/_new.html.erb
<div class="box">
  <%= render 'form' %>
</div>

app/views/partials/admin/_page_title.html.erb
<div class="page_title">
  <div class="container" id="page_title">
    <div class="span-16">
      <h2><%= page[:title] || t('hello') %>
        <span class="page_title_options">
          <%= yield(:page_title_options) %>
        </span>
      </h2>
    </div>
    <div class="span-8 last">
    </div>
  </div>
</div>

app/views/partials/admin/_show.html.erb
<div class="box">
  <% content_for(:toolbar) do %>
    <%= link_btn t("common.link_back"), 'javascript:void(0);', :icon => :prev, :onclick => 'self.history.back(); return false;' %>
    <%= link_btn t("admin.common.edit_link"), edit_resource_path(resource), :icon => :edit %>
    <%= begin
      link_btn t("admin.common.frontend_show_link"), resource, :icon => :show 
      rescue
      end
    %>
  <% end %>
  <%#= debug resource.attributes %>
</div>

app/views/partials/admin/_sidebar.html.erb
<div id="sidebar" class="span-8 last">
  <%= yield(:sidebar) %>
</div>

app/views/partials/admin/_sidebar_company_info.html.erb
<% content_for(:sidebar) do %>
  <div class="box">
    <h3>
      <%= t "common.sidebar.company_information.header" %>
      <%= link_btn t("common.sidebar.company_information.show"), admin_company_path(company), :class => 'show', :icon => :show %>
    </h3>

    <table>
      <thead>
        <tr>
          <th colspan="2">
            <b><%= company.name %></b>
            <%= link_btn t("common.sidebar.company_information.edit"), edit_admin_company_path(company), :icon => :edit %>
          </th>
        </tr>
      </thead>
      <% %w(address address2 zip city country phone fax email website).each do |attr| %>
        <% if company[attr].full? %>
          <tr>
            <th><%= Company.human_attribute_name(attr) %></th>
            <td><%= contact_info(company, attr)%></td>
          </tr>
        <% end %>
      <% end %>
    </table>

  </div>
<% end %>

app/views/partials/admin/_sidebar_person_info.html.erb
<% content_for(:sidebar) do %>
  <div class="box">
    <h3>
      <%= t "common.sidebar.person_information.header" %>
      <%= link_btn t("common.sidebar.person_information.show"), admin_person_path(person), :class => 'show', :icon => :show %>
    </h3>

    <table>
      <thead>
        <tr>
          <th colspan="2">
            <b><%= person.name %></b>
            <%= link_btn t("common.sidebar.person_information.edit"), edit_admin_person_path(person), :icon => :edit %>
          </th>
        </tr>
      </thead>
      <% %w(phone fax email website).each do |attr| %>
        <% if person[attr].full? %>
          <tr>
            <th><%= Person.human_attribute_name(attr) %></th>
            <td><%= contact_info(person, attr)%></td>
          </tr>
        <% end %>
      <% end %>
    </table>

  </div>
<% end %>

app/views/partials/admin/_table.html.erb
<% model.new.attributes.keys.tap do |attributes| %>
<table>
  <thead>
    <tr>
      <th>id</th>
      <% attributes.each do |attr| %>
        <th><%= attr.humanize %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% arel.each do |ar| %>
      <tr>
        <td><%= ar.id %></th>
        <% attributes.each do |attr| %>
        <td><%= ar[attr].is_a?(Hash) ? debug(ar[attr]) : ar[attr] %></td>
        <% end %>
        <td><%= link_to "Edit", {:action => 'edit', :id => ar}, :class => 'edit' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>